import React from 'react';
import GenericProductPage from './GenericProductPage';
import { useUI } from '../context/UIContext';

export const DSCRLoans: React.FC = () => {
  const { openInquiry } = useUI();
  return (
    <GenericProductPage 
      onOpenInquiry={openInquiry}
    badge="Investors"
    title="DSCR Investor Loans"
    description="No personal income verification. Qualification based strictly on the property's rental income — a lifeline for real estate investors."
    image="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200"
    overview="The Debt Service Coverage Ratio (DSCR) is a financial metric used by lenders to assess a borrower's ability to cover their debt obligations. DSCR loans are technically classified as Non-QM loans that cater specifically to real estate investors. They evaluate cash flow generated by investment properties rather than relying on pay stubs or W-2 forms. Since investment property deductions can significantly reduce taxable income, DSCR loans play a pivotal role in determining whether borrowers can comfortably manage loan repayments. The DSCR formula: DSCR = Net Operating Income (NOI) / Total Debt Service."
    benefits={[
      { title: "No Tax Returns Needed", desc: "Keep your personal finances private. No W-2s, pay stubs, or complex tax reviews required. Perfect for investors with many write-offs." },
      { title: "Infinite Scalability", desc: "Build a large portfolio without being limited by your personal income-to-debt ratio. Qualification is per-property, not per-person." },
      { title: "LLC Vesting", desc: "Close in the name of your company to protect your personal assets. Ideal for investors structuring through business entities." }
    ]}
    process={[
      { title: "Property assessment", desc: "Lenders assess the property's projected income and operating expenses." },
      { title: "DSCR calculation", desc: "Calculate the Debt Service Coverage Ratio. A good ratio typically falls in the range of 1.25 to 1.5 or higher." },
      { title: "Loan approval", desc: "If the DSCR meets the lender's criteria, the loan is approved based on property cash flow." },
      { title: "Repayment", desc: "Borrowers make regular payments based on the property's rental income." }
    ]}
    faqs={[
      { q: "What is a good DSCR ratio?", a: "A good DSCR ratio typically falls in the range of 1.25 to 1.5 or higher. This means the property generates enough income to cover its debt service by 1.25 to 1.5 times, providing a cushion for unexpected expenses." },
      { q: "Can I use this for short-term rentals?", a: "Yes, many DSCR programs now support Airbnb and VRBO properties in addition to traditional long-term rentals." },
      { q: "What is the DSCR formula?", a: "DSCR = Net Operating Income (NOI) / Total Debt Service. A ratio greater than 1 indicates the property generates more income than needed to cover payments." },
      { q: "Is a down payment required?", a: "Yes, investors typically need 20% to 25% down for DSCR loans." }
    ]}
  />
  );
};

export const CashOutRefinance: React.FC = () => {
  const { openInquiry } = useUI();
  return (
    <GenericProductPage 
      onOpenInquiry={openInquiry}
    badge="Refinance"
    title="Cash-Out Refinancing"
    description="Unlock the equity in your home. Consolidate debt, fund renovations, pay for college, or start a business."
    image="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=1200"
    overview="Refinancing replaces your current mortgage with a new one — potentially with a lower rate, different term, or cash from your equity. Whether you're tired of an adjustable rate, want to eliminate PMI, or need cash for home improvements, refinancing can solve many mortgage challenges. At Assurant Home Loans, our staff of refinance experts will evaluate your needs and draft a plan that saves you money. A typical refinance takes 2 to 4 weeks."
    benefits={[
      { title: "Lower Monthly Payment", desc: "Obtain a lower interest rate or extend your term. Switch from variable to fixed rate for stability and predictability." },
      { title: "Cash-Out Equity", desc: "Access the equity in your home for bills, college, renovation, starting a business, or consolidating high-interest debt." },
      { title: "Drop PMI", desc: "If your home value has increased and you have 20%+ equity, you can refinance to eliminate Private Mortgage Insurance entirely." }
    ]}
    process={[
      { title: "Equity check", desc: "Determine how much you can borrow — typically up to 80% of home value." },
      { title: "Application", desc: "Apply for a new loan covering your balance plus the cash you need." },
      { title: "Appraisal", desc: "Verify your home's current market value. This is where most hang-ups occur, so schedule early." },
      { title: "Closing", desc: "Sign the papers and receive your cash via wire or check. Closing costs typically run 1% to 2% of the loan amount." }
    ]}
    faqs={[
      { q: "What is the 2% rule?", a: "The 2% rule states you should aim for a 2% lower interest rate to offset refinancing costs, provided you've lived in your home for 2 years and plan to stay 2 more. However, even a 1% reduction can pay off if you plan to stay 5+ years." },
      { q: "What does refinancing cost?", a: "Typically 1% to 2% of the loan amount, including lender fees. Low- and no-cost refinancing options are available." },
      { q: "What are points?", a: "Discount points are a way of lowering your interest rate. By paying 1% of the total loan amount up-front, you can lower your rate by about 1/8%." },
      { q: "Do I need equity to refinance?", a: "Yes. The general rule is a 90% loan-to-value ratio (10% equity minimum). Your home must have increased in value since purchase." },
      { q: "Can I get cash from a refinance?", a: "Yes. Depending on the type of refinance, you can take out cash for bills, home repairs, or whatever you need." }
    ]}
  />
  );
};

export const BankStatementLoans: React.FC = () => {
  const { openInquiry } = useUI();
  return (
    <GenericProductPage 
      onOpenInquiry={openInquiry}
    badge="Investors"
    title="Bank Statement Loans"
    description="Flexible solutions for self-employed borrowers. Qualify using your bank deposits rather than W-2s or tax returns."
    image="https://images.unsplash.com/photo-1554224154-156c703e8787?auto=format&fit=crop&q=80&w=1200"
    overview="At Assurant Home Loans, we understand that traditional income documentation doesn't always reflect your financial situation — especially for self-employed individuals. Bank Statement Loans allow you to qualify for a mortgage based on your bank deposits rather than W-2s or tax returns. This loan is ideal for small business owners, freelancers, contractors, and other self-employed professionals who have solid income but can't meet strict conventional requirements."
    benefits={[
      { title: "Income via Bank Statements", desc: "Instead of relying on W-2s or tax returns, your monthly deposits are reviewed to determine qualifying income. No tax returns required." },
      { title: "Self-Employed Friendly", desc: "Designed specifically for freelancers, consultants, contractors, small business owners, and anyone with irregular or fluctuating income." },
      { title: "Competitive Rates", desc: "Benefit from attractive rates tailored to your financial situation. Flexible terms with a simplified application process." }
    ]}
    process={[
      { title: "Statement review", desc: "Submit 12 or 24 months of consecutive personal or business bank statements." },
      { title: "Expense ratio", desc: "We calculate a business expense ratio to determine your qualifying income from deposits." },
      { title: "Credit check", desc: "Standard credit scores apply, typically 640 or higher for qualification." },
      { title: "Funding", desc: "Close your loan and get back to running your business. Process is streamlined for speed." }
    ]}
    faqs={[
      { q: "Can I use personal statements?", a: "Yes, both personal and business bank statements are acceptable for qualification." },
      { q: "Is the interest rate higher?", a: "Slightly higher than conventional, reflecting the non-traditional verification method. However, rates remain competitive." },
      { q: "Do I need a business license?", a: "Generally yes, to prove you have been in business for at least 2 years. This helps establish income stability." },
      { q: "Who should consider a Bank Statement Loan?", a: "Self-employed individuals, freelancers, consultants, contractors, small business owners, and anyone whose income doesn't fit traditional loan guidelines." }
    ]}
  />
  );
};

export const NonQMLoans: React.FC = () => {
  const { openInquiry } = useUI();
  return (
    <GenericProductPage 
      onOpenInquiry={openInquiry}
    badge="Investors"
    title="Non-QM Specialist Loans"
    description="Mortgage solutions for those who don't fit in traditional boxes — self-employed, foreign nationals, and complex income situations."
    image="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200"
    overview="Non-Qualified Mortgage (Non-QM) loans are for borrowers who may not qualify for conventional loans. After the 2008 mortgage crisis, federal regulators tightened requirements on 'qualified mortgages.' Non-QM loans fall outside those qualifications but are not necessarily riskier — all borrowers must still prove ability to repay. They employ non-standard terms like longer loan periods, interest-only options, higher debt ratios, or alternate income verification. Interest rates tend to be 0.5% to 5% higher, depending on terms."
    benefits={[
      { title: "Self-Employed Solutions", desc: "Self-employed individuals can qualify using bank statements. Real estate investors can use projected rental income. No standard income docs needed." },
      { title: "Loans up to $2.5 Million", desc: "Fixed-rate and adjustable-rate options available. No mortgage insurance required. Can be made to legal entities like family trusts." },
      { title: "Credit Recovery Options", desc: "Available for those recovering from bankruptcy, foreclosure, or short sales. Also excellent for foreign nationals buying US property without a US credit score." }
    ]}
    process={[
      { title: "Unique discovery", desc: "Explain your specific scenario — our Non-QM specialists evaluate each case individually." },
      { title: "Solution design", desc: "We match you with a niche investor that understands your unique financial profile." },
      { title: "Holistic underwriting", desc: "A human expert reviews bank statements, investment accounts, or asset documentation. Credit scores and DTI are factored in but not sole determinants." },
      { title: "Closing", desc: "Non-QM loans close just as quickly as conventional mortgages. Cash-out refinance allows up to $500,000 in equity withdrawal." }
    ]}
    faqs={[
      { q: "Who do Non-QM loans help?", a: "Self-employed borrowers, those with considerable assets, real estate investors (especially flippers), foreign buyers without US credit scores, and buyers with blemished credit histories." },
      { q: "What types are available?", a: "Loan terms longer than 30 years, interest-only loans, higher debt ratio acceptance, and alternate income verification. Available for primary residence, refinance, cash-out, and investment property." },
      { q: "Is mortgage insurance required?", a: "No, mortgage insurance is not required on Non-QM loans — a major advantage over FHA and some conventional products." },
      { q: "How big are the loans?", a: "Non-QM loans can go up to $2.5 million or more, often exceeding conventional limits. Cash-out refinance allows up to $500,000 in equity." }
    ]}
  />
  );
};

export const ReverseMortgage: React.FC = () => {
  const { openInquiry } = useUI();
  return (
    <GenericProductPage 
      onOpenInquiry={openInquiry}
    badge="Refinance"
    title="Reverse Mortgage (HECM)"
    description="Financial freedom for seniors 62+. Convert home equity into cash — receive monthly installments, a lump sum, or a line of credit."
    image="https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=1200"
    overview="A reverse mortgage loan is different than a traditional mortgage. Instead of you making monthly payments to the lender, the lender pays you — through monthly installments, a one-time lump sum, a line of credit, or a combination. The amount you receive depends on your age, home value, and current interest rate. You are not required to pay the loan back until the home is no longer your primary residence. A federally insured HECM reverse mortgage helps you unlock your equity while staying in your home."
    benefits={[
      { title: "No Monthly Payments", desc: "Eliminate your current mortgage payment. The loan is not repaid until you sell, move out permanently, or pass away." },
      { title: "Retain Ownership", desc: "You keep the title to your home and can live there indefinitely, as long as you pay property taxes, insurance, and maintain the home." },
      { title: "Flexible Payouts", desc: "Choose a lump sum, monthly installments, a line of credit, or any combination — tailored to your retirement cash flow needs." }
    ]}
    process={[
      { title: "Research options", desc: "Speak with our mortgage professionals about reverse mortgage types and determine which suits your situation." },
      { title: "HUD counseling", desc: "Complete a required session with a HUD-approved counselor. Independent counseling typically costs $125." },
      { title: "Application & appraisal", desc: "Submit your application. A licensed appraiser inspects and values your property. Any significant problems must be fixed first." },
      { title: "Closing & payments", desc: "Review terms, sign paperwork. After a 3-day grace period, you start receiving proceeds in your chosen format." }
    ]}
    faqs={[
      { q: "What is the minimum age?", a: "The primary borrower must be at least 62 years old. The home must be your primary residence." },
      { q: "When is the loan repaid?", a: "When the homeowner passes away, sells the home, lives elsewhere for 12+ consecutive months, or fails to pay property taxes/insurance." },
      { q: "Will I lose my home?", a: "No, as long as you pay property taxes, homeowner's insurance, and maintain the home. You retain full title and ownership." },
      { q: "What types of homes qualify?", a: "Single-family units and HUD-approved condominiums typically qualify. Most mobile homes and co-ops are generally not eligible." },
      { q: "What are the costs?", a: "Costs include an origination fee (up to $6,000), appraisal fees, mortgage insurance premium (0.5% or 2.5% initial, plus 1.25% annual), and standard closing costs." }
    ]}
  />
  );
};
